# Generated by Django 4.1.1 on 2022-09-20 20:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=300)),
                ('photo', models.ImageField(default='profile/avatar.png', null=True, upload_to='profile')),
                ('social_instagram', models.CharField(blank=True, max_length=300, null=True)),
                ('social_website', models.CharField(blank=True, max_length=300, null=True)),
                ('social_facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('social_twitter', models.CharField(blank=True, max_length=300, null=True)),
                ('social_linkedin', models.CharField(blank=True, max_length=300, null=True)),
                ('social_email', models.CharField(blank=True, max_length=300, null=True)),
                ('social_youtube', models.CharField(blank=True, max_length=300, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='map.city')),
            ],
        ),
    ]
