# Generated by Django 4.1.1 on 2022-10-09 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=datetime.date(2022, 10, 9)),
            preserve_default=False,
        ),
    ]
