# Generated by Django 4.1.1 on 2022-09-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
