# Generated by Django 4.1.1 on 2022-10-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_user_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='community',
        ),
        migrations.AddField(
            model_name='event',
            name='communities',
            field=models.ManyToManyField(related_name='events', to='map.community'),
        ),
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
