# Generated by Django 4.1.1 on 2022-10-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_remove_event_community_event_communities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_core_team',
            field=models.BooleanField(default=False),
        ),
    ]
