# Generated by Django 4.1.1 on 2022-10-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_venue_remove_event_latitude_remove_event_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='venue_city', to='map.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='photo',
            field=models.ImageField(default='community/avatar.png', null=True, upload_to='community'),
        ),
        migrations.AlterField(
            model_name='community',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_city', to='map.city'),
        ),
    ]
