# Generated by Django 4.1.1 on 2022-10-06 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_venue_city_venue_photo_alter_community_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
    ]
