# Generated by Django 4.1.1 on 2022-10-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_remove_event_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='communities',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='map.community'),
        ),
    ]
